### ISSUE TITLE
S3 expect step

### ISSUE THREAD

**Issue by comtihon** [comtihon/catcher_modules#36]
Need an expect step to match file with S3:

```
- expect:
        compare:
              postgres:
                   config: '{{ s3_config }}'
                   data:
                        bucket/file: expect.csv
```
