### ISSUE TITLE
override variables for prepare step

### ISSUE THREAD

**Issue by comtihon** [comtihon/catcher_modules#52]
Prepare step should have option to override variables in order to use the same sql for different data generation without changing the state.
```
- prepare:
         populate:
           postgres:
                conf: '{{ postgres_conf }}'
                schema: create_personal_data_customer.sql
         variables:
           generated_customerNumber: '{{ generated_customerNumber1 }}'
           account_owner_id: '{{ account_owner_id1 }}'
           id_application: '{{ id_application1 }}'
           generated_id: '{{ generated_id1 }}'
           generated_id_public: '{{ generated_id_public1 }}'
           id: '{{ id1 }}'
```
