### ISSUE TITLE
rabbitmq consume does not work

### ISSUE THREAD

**Issue by aksenk** [comtihon/catcher_modules#57]
Rabbitmq config:
```
rabbitmq_conf:
  server: 127.0.0.1:5672
  username: 'guest'
  password: 'guest'
```

Test:
```
steps:
  - rabbit:
      name: 'Read message from rabbitmq'
      consume:
        config: '{{ rabbit_conf }}'
        queue: 'test'
```

Error:
```
INFO:catcher:Step Read message from rabbitmq [0s] failed: 'str' object has no attribute 'get'
WARNING:catcher:Test mq_getFilters failed: 'str' object has no attribute 'get'
```

Traceback:
```
Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/catcher-1.32.3-py3.7.egg/catcher/core/runner.py\", line 80, in _run_test\n    test.run()\n  File \"/usr/local/lib/python3.7/site-packages/catcher-1.32.3-py3.7.egg/catcher/core/test.py\", line 71, in run\n    if not self._run_step(step, tag, raise_stop):\n  File \"/usr/local/lib/python3.7/site-packages/catcher-1.32.3-py3.7.egg/catcher/core/test.py\", line 95, in _run_step\n    if not self._run_actions(step, action, action_object, self.variables, raise_stop, ignore_errors):\n  File \"/usr/local/lib/python3.7/site-packages/catcher-1.32.3-py3.7.egg/catcher/core/test.py\", line 132, in _run_actions\n    raise e\n  File \"/usr/local/lib/python3.7/site-packages/catcher-1.32.3-py3.7.egg/catcher/core/test.py\", line 105, in _run_actions\n    self.variables = action_object.action(self.includes, variables)\n  File \"/usr/local/lib/python3.7/site-packages/catcher-1.32.3-py3.7.egg/catcher/steps/step.py\", line 234, in wrapper\n    result = func(self, *args, **kwargs)\n  File \"/catcher_modules/catcher_modules/mq/rabbit.py\", line 115, in action\n    if config.get('virtualhost') is None:\nAttributeError: 'str' object has no attribute 'get'\n
```
