### ISSUE TITLE
Change airflow connections population

### ISSUE THREAD

**Issue by comtihon** [comtihon/catcher_modules#64]
add several additional fields: 
* type - if there is no type, this inventory record won't be added to airflow. If there is one - it will be used as connection type.
* extra - is a json **string** representing field extra in airflow connections as it should be
* url - url connection. If it doesn't exist (object configuration form - it should be composed)

examples:
string form
```
psql_conf:
    url: 'postgres:postgres@custom_postgres_1:5432/postgres'
    extra: '{"key": "value"}'
    type: 'postgres'
```
object form
```
psql_conf:
    dbname: test
    user: user
    password: password
    host: localhost
    port: 5433
    extra: '{"key": "value"}'
    type: 'postgres'
```
